#!/usr/bin/env bash
# Wraps raw puzzle object-literal fragments (each a sequence of
# "    { id:..., ... }," blocks, same shape as entries inside CASES.easy/medium/hard
# in puzzles.js) into a single new batch file that CASES.<tier>.push()es them at
# load time. This lets new puzzle batches be added as their own file — no more
# splicing lines into the giant puzzles.js — you just add a new <script> tag.
#
# Usage:
#   bash build-batch.sh <output-file> \
#     --easy   fragA.js fragB.js ... \
#     --medium fragC.js ... \
#     --hard   fragD.js ...
#
# Each fragment file must already be in "raw block" form, e.g.:
#     {
#       id:"easy-foo", date:"2026-08-27", answer:"...",
#       accept:[...],
#       clues:[...],
#       teach:"..."
#     },
#     { ... },
#
# Output file is meant to be included via a new <script src="..."></script>
# tag in index.html, placed AFTER puzzles.js and BEFORE main.js.

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: bash build-batch.sh <output-file> --easy f1 f2 ... --medium f3 ... --hard f4 ..."
  exit 1
fi

OUT="$1"; shift

EASY_FILES=()
MEDIUM_FILES=()
HARD_FILES=()
MODE=""

for arg in "$@"; do
  case "$arg" in
    --easy) MODE="easy" ;;
    --medium) MODE="medium" ;;
    --hard) MODE="hard" ;;
    *)
      case "$MODE" in
        easy) EASY_FILES+=("$arg") ;;
        medium) MEDIUM_FILES+=("$arg") ;;
        hard) HARD_FILES+=("$arg") ;;
        *) echo "Fragment '$arg' given before any --easy/--medium/--hard flag"; exit 1 ;;
      esac
      ;;
  esac
done

{
  echo "/* ---------- Additional puzzle batch (generated by build-batch.sh) ---------- */"
  if [ "${#EASY_FILES[@]}" -gt 0 ]; then
    echo "CASES.easy.push("
    cat "${EASY_FILES[@]}"
    echo ");"
  fi
  if [ "${#MEDIUM_FILES[@]}" -gt 0 ]; then
    echo "CASES.medium.push("
    cat "${MEDIUM_FILES[@]}"
    echo ");"
  fi
  if [ "${#HARD_FILES[@]}" -gt 0 ]; then
    echo "CASES.hard.push("
    cat "${HARD_FILES[@]}"
    echo ");"
  fi
} > "$OUT"

echo "Wrote $OUT"
echo "Don't forget to add: <script src=\"$(basename "$OUT")\"></script> to index.html, after puzzles.js and before main.js."
